question_data = [
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "easy",
      "question": "Who wrote and directed the 1986 film &#039;Platoon&#039;?",
      "correct_answer": "Oliver Stone",
      "incorrect_answers": ["Francis Ford Coppola", "Stanley Kubrick", "Michael Cimino"]},
     {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
      "question": "When was the programming language &quot;C#&quot; released?",
      "correct_answer": "2000", "incorrect_answers": ["1998", "1999", "2001"]},
     {"category": "History", "type": "boolean", "difficulty": "easy",
      "question": "The Spitfire originated from a racing plane.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Vehicles", "type": "multiple", "difficulty": "easy",
      "question": "Automobiles produced by Telsa Motors operate on which form of energy?",
      "correct_answer": "Electricity",
      "incorrect_answers": ["Gasoline", "Diesel", "Nuclear"]},
     {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
      "question": "What was Frank West&#039;s job in &quot;Dead Rising&quot;?",
      "correct_answer": "Photojournalist",
      "incorrect_answers": ["Janitor", "Chef", "Taxi Driver"]},
     {"category": "Science & Nature", "type": "multiple", "difficulty": "easy",
      "question": "The medical term for the belly button is which of the following?",
      "correct_answer": "Umbilicus", "incorrect_answers": ["Nevus", "Nares", "Paxillus"]},
     {"category": "History", "type": "multiple", "difficulty": "medium",
      "question": "Which country was an allied power in World War II?",
      "correct_answer": "Soviet Union", "incorrect_answers": ["Italy", "Germany", "Japan"]},
     {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
      "question": "If you are caught &quot;Goldbricking&quot;, what are you doing wrong?",
      "correct_answer": "Slacking",
      "incorrect_answers": ["Smoking", "Stealing", "Cheating"]},
     {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
      "question": "Which of the following spacecraft never touched the moon?",
      "correct_answer": "Mariner 4",
      "incorrect_answers": ["Apollo 11", "Luna 2", "SMART-1"]},
     {"category": "Sports", "type": "multiple", "difficulty": "hard",
      "question": "Which of these Russian cities did NOT contain a stadium that was used in the 2018 FIFA World Cup?",
      "correct_answer": "Vladivostok",
      "incorrect_answers": ["Rostov-on-Don", "Yekaterinburg", "Kaliningrad"]}

]
